# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By


class TestExploreSelenium:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_exploreSelenium(self):
        self.driver.get("http://localhost:5000/")
        self.driver.set_window_size(1290, 741)
        self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(3) .align-middle:nth-child(2)").click()
        self.driver.find_element(By.ID, "add-btn-2").click()
        element = self.driver.find_element(By.ID, "add-btn-2")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.ID, "add-btn-1").click()
        self.driver.find_element(By.ID, "open-download-modal-btn").click()
        self.driver.find_element(By.ID, "zip-filename").click()
        self.driver.find_element(By.ID, "zip-filename").send_keys("Sample Dataset 5")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-success:nth-child(1)").click()
        self.driver.find_element(By.ID, "create-dataset-btn").click()
        self.driver.find_element(By.ID, "dataset-title").click()
        self.driver.find_element(By.ID, "dataset-title").send_keys("Sample Dataset 5")
        self.driver.find_element(By.ID, "dataset-description").click()
        self.driver.find_element(By.ID, "dataset-description").click()
        element = self.driver.find_element(By.ID, "dataset-description")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.ID, "dataset-description").click()
        self.driver.find_element(By.ID, "dataset-description").send_keys("Test")
        self.driver.find_element(By.ID, "dataset-tags").click()
        self.driver.find_element(By.ID, "dataset-tags").send_keys("tag2")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(1)").click()
        self.driver.find_element(By.ID, "my-selected-datasets-section").click()
        self.driver.find_element(By.ID, "my-selected-datasets-section").click()
